# Generated by Django 5.1.5 on 2025-01-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('subjects', models.CharField(max_length=300, null=True)),
                ('message', models.TextField()),
                ('action_taken', models.TextField()),
            ],
        ),
    ]
