# Generated by Django 5.1.5 on 2025-01-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_status',
            field=models.CharField(max_length=100),
        ),
    ]
