# Generated by Django 5.1.5 on 2025-01-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='allowance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
