# Generated by Django 5.1.5 on 2025-01-31 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_payroll_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='emp_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employees'),
        ),
    ]
