# Generated by Django 5.1.5 on 2025-01-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_attendance_time_in_alter_attendance_time_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='action',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
