# Generated by Django 5.1.5 on 2025-02-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='action',
            field=models.TextField(blank=True),
        ),
    ]
