# Generated by Django 5.1.5 on 2025-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_feedback_address_feedback_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='action',
            field=models.TextField(blank=True),
        ),
    ]
